version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_production

  web:
    build: .
    ports:
         - "0.0.0.0:3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@db/myapp_production
      RAILS_MASTER_KEY: 27be1f03d9b3370a04277582aa56e146  # Replace this with the actual key from `config/master.key`

volumes:
  postgres_data:
